services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=things'
      - 'POSTGRES_PASSWORD=things12345'
      - 'POSTGRES_USER=things_service'
      - 'POSTGRES_SCHEMA=things'
    ports:
      - '5432:5432'
networks:
  db:
    driver: bridge

volumes:
  db:
