services:
  postgres:
    image: 'postgres:latest'
    command: postgres -c max_connections=200
    environment:
      - 'POSTGRES_DB=things'
      - 'POSTGRES_PASSWORD=things12345'
      - 'POSTGRES_USER=things_service'
      - 'POSTGRES_SCHEMA=things'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db
networks:
  db:
    driver: bridge

volumes:
  db:
