spring:
  profiles:
    active: dev
  docker:
    compose:
      profiles:
        active: dev
  security:
    user:
      name: user
      password: user
  application:
    name: Property accountant service
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/things
    username: things_service
    password: things12345
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
things:
  jwt:
    key: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4
    header: Authorization
    expiration: 86400000 # a day
    refresh-token-expiration: 604800000 # 7 days

