export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
export const FETCH_PLACES_FAILURE = "FETCH_PLACES_FAILURE";
export const FETCH_PLACE_SUCCESS = "FETCH_PLACE_SUCCESS";
export const CREATE_PLACE_SUCCESS = "CREATE_PLACE_SUCCESS";
export const DELETED_PLACE_SUCCESS = "DELETED_PLACE_SUCCESS";
export const UPDATE_PLACE_SUCCESS = "UPDATE_PLACE_SUCCESS";
export const API_LOADING = 'API_LOADING';