TRUNCATE TABLE things.pdfbooks_categories RESTART IDENTITY;
INSERT INTO things.pdfbooks_categories (id, name) VALUES
    (1, 'Advanced Level'),
    (2, 'Beginner Level'),
    (3, 'C'),
    (4, 'C#'),
    (5, 'C++'),
    (6, 'Case Studies'),
    (7, 'Cassandra'),
    (8, 'Columnar Databases'),
    (9, 'Cookbooks'),
    (10, 'CouchDB'),
    (11, 'Data Science & Machine Learning'),
    (12, 'Databases & Data Storage'),
    (13, 'DevOps & System Administration'),
    (14, 'Document Databases'),
    (15, 'DynamoDB'),
    (16, 'Elasticsearch'),
    (17, 'Firebase Realtime Database'),
    (18, 'Go'),
    (19, 'Graph Databases'),
    (20, 'InfluxDB'),
    (21, 'Intermediate Level'),
    (22, 'Java'),
    (23, 'JavaScript'),
    (24, 'Key-Value Stores'),
    (25, 'Kotlin'),
    (26, 'MariaDB'),
    (27, 'Microsoft SQL Server'),
    (28, 'MongoDB'),
    (29, 'Monographs'),
    (30, 'MySQL'),
    (31, 'Neo4j'),
    (32, 'Networking & Security'),
    (33, 'NoSQL Databases'),
    (34, 'Oracle Database'),
    (35, 'PHP'),
    (36, 'PostgreSQL'),
    (37, 'Practical'),
    (38, 'Programming'),
    (39, 'Python'),
    (40, 'Reference Guides'),
    (41, 'Redis'),
    (42, 'Relational Databases'),
    (43, 'Ruby'),
    (44, 'Rust'),
    (45, 'Software Architecture'),
    (46, 'SQLite'),
    (47, 'Swift'),
    (48, 'Textbooks'),
    (49, 'Theoretical'),
    (50, 'Time-Series Databases'),
    (51, 'Tutorials'),
    (52, 'White Papers');