INSERT INTO things.pdfbooks_categories (id, name) VALUES
                                      (1, 'Textbooks'),
                                      (2, 'Tutorials'),
                                      (3, 'Reference Guides'),
                                      (4, 'Cookbooks'),
                                      (5, 'Monographs'),
                                      (6, 'White Papers'),
                                      (7, 'Beginner Level'),
                                      (8, 'Intermediate Level'),
                                      (9, 'Advanced Level'),
                                      (10, 'Theoretical'),
                                      (11, 'Practical'),
                                      (12, 'Case Studies'),
                                      (13, 'Programming'),
                                      (14, 'DevOps & System Administration'),
                                      (15, 'Networking & Security'),
                                      (16, 'Databases & Data Storage'),
                                      (17, 'Data Science & Machine Learning'),
                                      (18, 'Software Architecture'),

-- Programming Languages
                                      (19, 'Java'),
                                      (20, 'JavaScript'),
                                      (21, 'Python'),
                                      (22, 'C'),
                                      (23, 'C++'),
                                      (24, 'C#'),
                                      (25, 'Go'),
                                      (26, 'Rust'),
                                      (27, 'Kotlin'),
                                      (28, 'Swift'),
                                      (29, 'PHP'),
                                      (30, 'Ruby'),

-- Database Types
                                      (31, 'Relational Databases'),
                                      (32, 'NoSQL Databases'),
                                      (33, 'Key-Value Stores'),
                                      (34, 'Document Databases'),
                                      (35, 'Columnar Databases'),
                                      (36, 'Graph Databases'),
                                      (37, 'Time-Series Databases'),

-- Concrete Databases
                                      (38, 'PostgreSQL'),
                                      (39, 'MySQL'),
                                      (40, 'MariaDB'),
                                      (41, 'Oracle Database'),
                                      (42, 'Microsoft SQL Server'),
                                      (43, 'SQLite'),
                                      (44, 'MongoDB'),
                                      (45, 'Redis'),
                                      (46, 'Cassandra'),
                                      (47, 'CouchDB'),
                                      (48, 'Elasticsearch'),
                                      (49, 'Neo4j'),
                                      (50, 'InfluxDB'),
                                      (51, 'DynamoDB'),
                                      (52, 'Firebase Realtime Database');