TRUNCATE TABLE things.authors RESTART IDENTITY;

INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Amos Wenger', 'Rust'),
       ('Andrei Alexandrescu', 'C++'),
       ('Andrew Barto', 'Reinforcement Learning'),
       ('Andrew Honig', 'reverse engineering'),
       ('Andrew Hunt', 'Pragmatic Programmer'),
       ('Andrew Ng', 'Machine Learning'),
       ('Andrew S. Tanenbaum', 'Computer Systems'),
       ('Andrew Tanenbaum', 'операционные системы, сети'),
       ('Andriy Burkov', 'Machine Learning'),
       ('Anthony Williams', 'C++ Concurrency');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Antti Laaksonen', 'Competitive Programming'),
       ('Arnold Robbins', 'Unix'),
       ('Aurélien Géron', 'Machine Learning'),
       ('Avdi Grimm', 'Ruby'),
       ('Avi Wigderson', 'Theoretical Computer Science'),
       ('Axel Rauschmayer', 'JavaScript'),
       ('Behrouz Forouzan', 'компьютерные сети'),
       ('Benjamin Pierce', 'Type Systems'),
       ('Bert Bates', 'Java'),
       ('Bilgin Ibryam', 'Cloud Native');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Bjarne Stroustrup', 'C++'),
       ('Brendan Burns', 'Kubernetes'),
       ('Brett Slatkin', 'Python'),
       ('Brian Goetz', 'Java Concurrency'),
       ('Brian Kernighan', 'C, Unix'),
       ('Bruce Davie', 'Networking'),
       ('Bruce Eckel', 'Java, C++'),
       ('Bruce Momjian', 'PostgreSQL'),
       ('Bruce Schneier', 'криптография, безопасность'),
       ('C.J. Date', 'реляционная теория');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Carol Nichols', 'Rust'),
       ('Cay Horstmann', 'Java'),
       ('Ceriel Jacobs', 'компиляторы'),
       ('Chad Fowler', 'Ruby, Career'),
       ('Charles E. Leiserson', 'алгоритмы'),
       ('Charlie Kaufman', 'сетевые протоколы безопасности'),
       ('Chris Eagle', 'reverse engineering'),
       ('Chris Okasaki', 'Functional Data Structures'),
       ('Chris Richardson', 'микросервисы'),
       ('Christian Antognini', 'Oracle Performance');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Christian Huitema', 'Internet Protocols'),
       ('Christopher Bishop', 'Machine Learning'),
       ('Claus Matzinger', 'Rust'),
       ('Clifford Stein', 'алгоритмы'),
       ('Craig Walls', 'Spring Framework'),
       ('Curtis R. Lueker', 'Algorithms'),
       ('Dan Abramov', 'React'),
       ('Daniel Bovet', 'Linux Internals'),
       ('Daniel Robbins', 'Linux'),
       ('Dave Thomas', 'Ruby');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('David Beazley', 'Python'),
       ('David Flanagan', 'JavaScript'),
       ('David Patterson', 'Computer Architecture'),
       ('David Thomas', 'Pragmatic Programmer'),
       ('David Vandevoorde', 'C++ Templates'),
       ('Dennis Ritchie', 'C, Unix'),
       ('Dennis Yurichev', 'reverse engineering'),
       ('Dick Grune', 'компиляторы'),
       ('Donald Chandra', 'Computer Science'),
       ('Donald Knuth', 'алгоритмы, теория программирования');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Douglas Comer', 'компьютерные сети'),
       ('Douglas Crockford', 'JavaScript'),
       ('Douglas Schmidt', 'Distributed Computing'),
       ('Ed Skoudis', 'security'),
       ('Edsger Dijkstra', 'алгоритмы, теория'),
       ('Elmasri Navathe', 'базы данных'),
       ('Eric Cole', 'security'),
       ('Eric Elliott', 'JavaScript'),
       ('Eric Foster-Johnson', 'Linux'),
       ('Eric Matthes', 'Python');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Eric Raymond', 'Unix'),
       ('Erich Gamma', 'паттерны проектирования'),
       ('Erik Demaine', 'Algorithms'),
       ('Fabien Coelho', 'PostgreSQL'),
       ('Fluent Python Author', 'Python'),
       ('Francesco Cesarini', 'Erlang'),
       ('Fred Brooks', 'управление проектами'),
       ('George Coulouris', 'Distributed Systems'),
       ('Georgia Weidman', 'penetration testing'),
       ('Gerald Weinberg', 'психология программирования');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Graham Hutton', 'Haskell'),
       ('Grant Fritchey', 'SQL Server производительность'),
       ('Greg Gagne', 'операционные системы'),
       ('Greg Kroah-Hartman', 'Linux Kernel'),
       ('Gregor Hohpe', 'Enterprise Integration'),
       ('Gregory Brown', 'Rust'),
       ('Hadley Wickham', 'R Programming, Data Science'),
       ('Herb Sutter', 'C++'),
       ('Herbert Bos', 'операционные системы'),
       ('Herbert Schildt', 'Java, C, C++');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Hugh Darwen', 'реляционная теория'),
       ('Ian Goodfellow', 'Machine Learning, Deep Learning'),
       ('Itzik Ben-Gan', 'SQL Server'),
       ('Jake VanderPlas', 'Data Science, Python'),
       ('James Kurose', 'Computer Networks'),
       ('Jason Orendorff', 'Rust'),
       ('Jean Dollimore', 'Distributed Systems'),
       ('Jeff Erickson', 'Algorithms'),
       ('Jeffrey Richter', '.NET'),
       ('Jeffrey Ullman', 'компиляторы, алгоритмы');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Jennifer Widom', 'базы данных'),
       ('Jerome Friedman', 'Statistical Learning'),
       ('Jim Blandy', 'Rust'),
       ('Joe Armstrong', 'Erlang'),
       ('Joe Beda', 'Kubernetes'),
       ('Joe Celko', 'SQL, базы данных'),
       ('Johannes Gehrke', 'базы данных'),
       ('John Hennessy', 'Computer Architecture'),
       ('John Hopcroft', 'Theory of Computation'),
       ('John Hughes', 'Functional Programming');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('John Lakos', 'C++ архитектура'),
       ('John Paul Shen', 'Computer Architecture'),
       ('John Resig', 'JavaScript'),
       ('John Vlissides', 'паттерны проектирования'),
       ('Jon Bentley', 'алгоритмы'),
       ('Jon Erickson', 'hacking'),
       ('Jon Gjengset', 'Rust'),
       ('Jonathan Corbet', 'Linux Kernel'),
       ('Jonathan Lewis', 'Oracle Database'),
       ('Joseph Albahari', '.NET');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Joshua Bloch', 'Java'),
       ('Justin Garrison', 'Kubernetes'),
       ('Justin Seitz', 'security, Python'),
       ('Kai Hwang', 'Computer Architecture'),
       ('Kalen Delaney', 'SQL Server'),
       ('Kathy Sierra', 'Java'),
       ('Keith Cooper', 'компиляторы'),
       ('Keith Ross', 'Computer Networks'),
       ('Kelsey Hightower', 'Kubernetes'),
       ('Kent Beck', 'TDD, Extreme Programming');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Kevin Mitnick', 'безопасность'),
       ('Kevin Murphy', 'Machine Learning'),
       ('Kevin Wayne', 'алгоритмы'),
       ('Kim Zetter', 'кибербезопасность'),
       ('Kyle Simpson', 'JavaScript'),
       ('Larry Peterson', 'Networking'),
       ('Lee Atchison', 'Cloud Architecture'),
       ('Leo Hsu', 'PostgreSQL'),
       ('Leonard Kleinrock', 'Computer Networks'),
       ('Leslie Lamport', 'распределенные системы');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Linda Torczon', 'компиляторы'),
       ('Liz Rice', 'Containers, Security'),
       ('Luca Palmieri', 'Rust'),
       ('Luciano Ramalho', 'Python'),
       ('Maarten van Steen', 'Distributed Systems'),
       ('Marco Cesati', 'Linux Internals'),
       ('Marijn Haverbeke', 'JavaScript'),
       ('Mario Fusco', 'современная Java'),
       ('Mark Lutz', 'Python'),
       ('Mark Richards', 'архитектура ПО');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Markus Winand', 'SQL производительность'),
       ('Marshall Kirk McKusick', 'BSD Unix'),
       ('Martin Abbott', 'Scalability'),
       ('Martin Fowler', 'архитектура ПО, рефакторинг'),
       ('Martin Kleppmann', 'Distributed Systems, Databases'),
       ('Michael Feathers', 'legacy code'),
       ('Michael Fisher', 'Scalability'),
       ('Michael Hartl', 'Ruby on Rails'),
       ('Michael Kerrisk', 'Linux Programming'),
       ('Michael Nygard', 'Software Architecture');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Michael Sikorski', 'reverse engineering'),
       ('Michael Sipser', 'Theory of Computation'),
       ('Miguel Revilla', 'Competitive Programming'),
       ('Mikito Takada', 'Microservices'),
       ('Mikko Hypponen', 'security'),
       ('Monica Lam', 'компиляторы'),
       ('Moozzyk', 'Modern C++'),
       ('Nancy Lynch', 'Distributed Systems'),
       ('Natan Silnitsky', 'Microservices'),
       ('Neal Ford', 'архитектура ПО');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Nicholas Zakas', 'JavaScript'),
       ('Nicolai Josuttis', 'C++ STL'),
       ('Nigel Poulton', 'Docker, Kubernetes'),
       ('Niklaus Wirth', 'Pascal, алгоритмы'),
       ('OccupyTheWeb', 'ethical hacking'),
       ('Pat Helland', 'Distributed Systems'),
       ('Peter Baer Galvin', 'операционные системы'),
       ('Peter Kim', 'penetration testing'),
       ('Peter Norvig', 'Artificial Intelligence'),
       ('Philip Wadler', 'Functional Programming');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Pierce Benjamin', 'Programming Languages'),
       ('Radia Perlman', 'сети, безопасность'),
       ('Raghu Ramakrishnan', 'базы данных'),
       ('Rajeev Motwani', 'Algorithms'),
       ('Ralph Johnson', 'паттерны проектирования'),
       ('Ramez Elmasri', 'базы данных'),
       ('Raoul-Gabriel Urma', 'современная Java'),
       ('Ravi Sethi', 'компиляторы'),
       ('Regina Obe', 'PostgreSQL'),
       ('Richard Bejtlich', 'network security');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Richard Bird', 'Functional Programming'),
       ('Richard Helm', 'паттерны проектирования'),
       ('Richard Sutton', 'Reinforcement Learning'),
       ('Rob Pike', 'Go, Unix'),
       ('Robert C. Martin', 'чистый код, SOLID'),
       ('Robert Love', 'Linux Kernel'),
       ('Robert Sedgewick', 'алгоритмы'),
       ('Robert Tibshirani', 'Statistical Learning'),
       ('Roberto Vitillo', 'Distributed Systems'),
       ('Rod Johnson', 'Spring Framework');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Roland Huß', 'Cloud Native'),
       ('Ronald Rivest', 'алгоритмы'),
       ('Ross Anderson', 'компьютерная безопасность'),
       ('Russ Olsen', 'Ruby'),
       ('Ryan Florence', 'React'),
       ('Sam Newman', 'микросервисы'),
       ('Sandi Metz', 'ООП'),
       ('Scott Meyers', 'C++'),
       ('Sebastian Raschka', 'Machine Learning'),
       ('Shamkant Navathe', 'базы данных');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Simon Peyton Jones', 'Haskell'),
       ('Stanley Lippman', 'C++'),
       ('Stephen Rago', 'Unix'),
       ('Steve Klabnik', 'Rust'),
       ('Steve McConnell', 'разработка ПО'),
       ('Steven Muchnick', 'компиляторы'),
       ('Steven Skiena', 'Algorithms'),
       ('Stoyan Stefanov', 'JavaScript'),
       ('Stuart Russell', 'Artificial Intelligence'),
       ('Ted Kaminski', 'Distributed Systems');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Thomas H. Cormen', 'алгоритмы'),
       ('Thomas Kyte', 'Oracle Database'),
       ('Tim Kindberg', 'Distributed Systems'),
       ('Tim Lister', 'разработка ПО'),
       ('Tim McNamara', 'Rust'),
       ('Tim Roughgarden', 'Algorithms'),
       ('Todd Austin', 'Computer Architecture'),
       ('Tom DeMarco', 'разработка ПО'),
       ('Tony Hoare', 'алгоритмы, языки программирования'),
       ('Torben Mogensen', 'компиляторы');
INSERT INTO things.pdfbooks_authors ("name", note)
VALUES ('Trevor Hastie', 'Statistical Learning'),
       ('Venkat Subramaniam', 'Java'),
       ('W. Richard Stevens', 'Unix, сети'),
       ('Wes McKinney', 'Data Science, Pandas'),
       ('William Dally', 'Computer Architecture'),
       ('William Stallings', 'сети, ОС, безопасность'),
       ('Yihui Xie', 'R Programming'),
       ('Yoshua Bengio', 'Machine Learning');
